//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAMMA
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="GX", ConfigurationName="WsAMMA.PPreConsuCli_V2_WSSoapPort")]
    public interface PPreConsuCli_V2_WSSoapPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GXaction/APPRECONSUCLI_V2_WS.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsAMMA.ExecuteResponse> ExecuteAsync(WsAMMA.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WSPreConsulta.WSPreCons", Namespace="GX")]
    public partial class WSPreConsultaWSPreCons
    {
        
        private string cUITField;
        
        private int nroDePrestamoField;
        
        private int secuenciaField;
        
        private double capitalFirmadoField;
        
        private double capitalNetoField;
        
        private System.Nullable<System.DateTime> fechaLiquidacionField;
        
        private short cuotasTotalesField;
        
        private short cuotasPagasField;
        
        private short cuotasRestantesField;
        
        private short cuotasEnMoraField;
        
        private double importeEnMoraField;
        
        private System.Nullable<System.DateTime> fechaDeUltimoPagoField;
        
        private System.Nullable<System.DateTime> ultimaCuotaPagaField;
        
        private double saldoParaCancelarField;
        
        private double saldoParaRefinanciarField;
        
        private double preSugeSalCanField;
        
        private double preSugeSalCanPunField;
        
        private double preSugeSalCanTotField;
        
        private double preSugeSalRenField;
        
        private double preSugeSalRenPunField;
        
        private double preSugeSalRenTotField;
        
        private string cliDesField;
        
        private string terrIDField;
        
        private string loLtIDField;
        
        private string ctoCrDesField;
        
        private string preEstDesField;
        
        private string preEstDesShField;
        
        private string preEstLiqDesField;
        
        private string preEstLiqDesShField;
        
        private string preVend2DesField;
        
        private int riePedIDField;
        
        private double preRetRenovField;
        
        private double preRetCtaSocField;
        
        private double preSisTasaField;
        
        private double preTEMField;
        
        private double preCFT_V1_CapFirmField;
        
        private double preCFT_V1_CapLiquiField;
        
        private double preCFT_V1_CapNetoField;
        
        private double prePriCtaField;
        
        private string preEstEsAprField;
        
        private string preEstLiqEsLiquiField;
        
        private double serviciosVigentesField;
        
        private WSPreConsultaWSPreConsWSPreConsCta[] wSPreConsultaCuotasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CUIT
        {
            get
            {
                return this.cUITField;
            }
            set
            {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NroDePrestamo
        {
            get
            {
                return this.nroDePrestamoField;
            }
            set
            {
                this.nroDePrestamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Secuencia
        {
            get
            {
                return this.secuenciaField;
            }
            set
            {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double CapitalFirmado
        {
            get
            {
                return this.capitalFirmadoField;
            }
            set
            {
                this.capitalFirmadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double CapitalNeto
        {
            get
            {
                return this.capitalNetoField;
            }
            set
            {
                this.capitalNetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FechaLiquidacion
        {
            get
            {
                return this.fechaLiquidacionField;
            }
            set
            {
                this.fechaLiquidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short CuotasTotales
        {
            get
            {
                return this.cuotasTotalesField;
            }
            set
            {
                this.cuotasTotalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public short CuotasPagas
        {
            get
            {
                return this.cuotasPagasField;
            }
            set
            {
                this.cuotasPagasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short CuotasRestantes
        {
            get
            {
                return this.cuotasRestantesField;
            }
            set
            {
                this.cuotasRestantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public short CuotasEnMora
        {
            get
            {
                return this.cuotasEnMoraField;
            }
            set
            {
                this.cuotasEnMoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double ImporteEnMora
        {
            get
            {
                return this.importeEnMoraField;
            }
            set
            {
                this.importeEnMoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> FechaDeUltimoPago
        {
            get
            {
                return this.fechaDeUltimoPagoField;
            }
            set
            {
                this.fechaDeUltimoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> UltimaCuotaPaga
        {
            get
            {
                return this.ultimaCuotaPagaField;
            }
            set
            {
                this.ultimaCuotaPagaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double SaldoParaCancelar
        {
            get
            {
                return this.saldoParaCancelarField;
            }
            set
            {
                this.saldoParaCancelarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double SaldoParaRefinanciar
        {
            get
            {
                return this.saldoParaRefinanciarField;
            }
            set
            {
                this.saldoParaRefinanciarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double PreSugeSalCan
        {
            get
            {
                return this.preSugeSalCanField;
            }
            set
            {
                this.preSugeSalCanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double PreSugeSalCanPun
        {
            get
            {
                return this.preSugeSalCanPunField;
            }
            set
            {
                this.preSugeSalCanPunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double PreSugeSalCanTot
        {
            get
            {
                return this.preSugeSalCanTotField;
            }
            set
            {
                this.preSugeSalCanTotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double PreSugeSalRen
        {
            get
            {
                return this.preSugeSalRenField;
            }
            set
            {
                this.preSugeSalRenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double PreSugeSalRenPun
        {
            get
            {
                return this.preSugeSalRenPunField;
            }
            set
            {
                this.preSugeSalRenPunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public double PreSugeSalRenTot
        {
            get
            {
                return this.preSugeSalRenTotField;
            }
            set
            {
                this.preSugeSalRenTotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CliDes
        {
            get
            {
                return this.cliDesField;
            }
            set
            {
                this.cliDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string TerrID
        {
            get
            {
                return this.terrIDField;
            }
            set
            {
                this.terrIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string LoLtID
        {
            get
            {
                return this.loLtIDField;
            }
            set
            {
                this.loLtIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CtoCrDes
        {
            get
            {
                return this.ctoCrDesField;
            }
            set
            {
                this.ctoCrDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PreEstDes
        {
            get
            {
                return this.preEstDesField;
            }
            set
            {
                this.preEstDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PreEstDesSh
        {
            get
            {
                return this.preEstDesShField;
            }
            set
            {
                this.preEstDesShField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string PreEstLiqDes
        {
            get
            {
                return this.preEstLiqDesField;
            }
            set
            {
                this.preEstLiqDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PreEstLiqDesSh
        {
            get
            {
                return this.preEstLiqDesShField;
            }
            set
            {
                this.preEstLiqDesShField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PreVend2Des
        {
            get
            {
                return this.preVend2DesField;
            }
            set
            {
                this.preVend2DesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int RiePedID
        {
            get
            {
                return this.riePedIDField;
            }
            set
            {
                this.riePedIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public double PreRetRenov
        {
            get
            {
                return this.preRetRenovField;
            }
            set
            {
                this.preRetRenovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public double PreRetCtaSoc
        {
            get
            {
                return this.preRetCtaSocField;
            }
            set
            {
                this.preRetCtaSocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public double PreSisTasa
        {
            get
            {
                return this.preSisTasaField;
            }
            set
            {
                this.preSisTasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public double preTEM
        {
            get
            {
                return this.preTEMField;
            }
            set
            {
                this.preTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public double PreCFT_V1_CapFirm
        {
            get
            {
                return this.preCFT_V1_CapFirmField;
            }
            set
            {
                this.preCFT_V1_CapFirmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public double PreCFT_V1_CapLiqui
        {
            get
            {
                return this.preCFT_V1_CapLiquiField;
            }
            set
            {
                this.preCFT_V1_CapLiquiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public double PreCFT_V1_CapNeto
        {
            get
            {
                return this.preCFT_V1_CapNetoField;
            }
            set
            {
                this.preCFT_V1_CapNetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public double PrePriCta
        {
            get
            {
                return this.prePriCtaField;
            }
            set
            {
                this.prePriCtaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string PreEstEsApr
        {
            get
            {
                return this.preEstEsAprField;
            }
            set
            {
                this.preEstEsAprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string PreEstLiqEsLiqui
        {
            get
            {
                return this.preEstLiqEsLiquiField;
            }
            set
            {
                this.preEstLiqEsLiquiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public double ServiciosVigentes
        {
            get
            {
                return this.serviciosVigentesField;
            }
            set
            {
                this.serviciosVigentesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=42)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WSPreConsCta", IsNullable=false)]
        public WSPreConsultaWSPreConsWSPreConsCta[] WSPreConsultaCuotas
        {
            get
            {
                return this.wSPreConsultaCuotasField;
            }
            set
            {
                this.wSPreConsultaCuotasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WSPreConsulta.WSPreCons.WSPreConsCta", Namespace="GX")]
    public partial class WSPreConsultaWSPreConsWSPreConsCta
    {
        
        private short renCtaNroField;
        
        private System.Nullable<System.DateTime> renCtaFeIniField;
        
        private System.Nullable<System.DateTime> renCtaFeVenField;
        
        private System.Nullable<System.DateTime> renCtaFePagField;
        
        private double renCtaCapField;
        
        private double renCtaIntField;
        
        private double renCtaPuraField;
        
        private double renCtaSeguroField;
        
        private double renCtaGasField;
        
        private double renCtaIVAField;
        
        private double renCtaCSField;
        
        private double renCtaACCField;
        
        private double renCtaOtrosField;
        
        private double renCtaTotalField;
        
        private double renCtaQuitaField;
        
        private double renCtaRecargoField;
        
        private double renCtaSaldoSinRecField;
        
        private double renCtaSaldoFinalField;
        
        private int renCtaMoraDiasField;
        
        private int renCtaMoraDiasAcuField;
        
        private string preRCtaLiqCodField;
        
        private string preCtaECodField;
        
        private double renSalCapField;
        
        private double renSalIntField;
        
        private double renSalIntIVAField;
        
        private double renSalGasField;
        
        private double renSalGasIVAField;
        
        private double renSalSegField;
        
        private double renPagosCtaField;
        
        private double renPagosPuntField;
        
        private double renPagosTotField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short RenCtaNro
        {
            get
            {
                return this.renCtaNroField;
            }
            set
            {
                this.renCtaNroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> RenCtaFeIni
        {
            get
            {
                return this.renCtaFeIniField;
            }
            set
            {
                this.renCtaFeIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> RenCtaFeVen
        {
            get
            {
                return this.renCtaFeVenField;
            }
            set
            {
                this.renCtaFeVenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> RenCtaFePag
        {
            get
            {
                return this.renCtaFePagField;
            }
            set
            {
                this.renCtaFePagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double RenCtaCap
        {
            get
            {
                return this.renCtaCapField;
            }
            set
            {
                this.renCtaCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double RenCtaInt
        {
            get
            {
                return this.renCtaIntField;
            }
            set
            {
                this.renCtaIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double RenCtaPura
        {
            get
            {
                return this.renCtaPuraField;
            }
            set
            {
                this.renCtaPuraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double RenCtaSeguro
        {
            get
            {
                return this.renCtaSeguroField;
            }
            set
            {
                this.renCtaSeguroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double RenCtaGas
        {
            get
            {
                return this.renCtaGasField;
            }
            set
            {
                this.renCtaGasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double RenCtaIVA
        {
            get
            {
                return this.renCtaIVAField;
            }
            set
            {
                this.renCtaIVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double RenCtaCS
        {
            get
            {
                return this.renCtaCSField;
            }
            set
            {
                this.renCtaCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double RenCtaACC
        {
            get
            {
                return this.renCtaACCField;
            }
            set
            {
                this.renCtaACCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double RenCtaOtros
        {
            get
            {
                return this.renCtaOtrosField;
            }
            set
            {
                this.renCtaOtrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double RenCtaTotal
        {
            get
            {
                return this.renCtaTotalField;
            }
            set
            {
                this.renCtaTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double RenCtaQuita
        {
            get
            {
                return this.renCtaQuitaField;
            }
            set
            {
                this.renCtaQuitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double RenCtaRecargo
        {
            get
            {
                return this.renCtaRecargoField;
            }
            set
            {
                this.renCtaRecargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double RenCtaSaldoSinRec
        {
            get
            {
                return this.renCtaSaldoSinRecField;
            }
            set
            {
                this.renCtaSaldoSinRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double RenCtaSaldoFinal
        {
            get
            {
                return this.renCtaSaldoFinalField;
            }
            set
            {
                this.renCtaSaldoFinalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int RenCtaMoraDias
        {
            get
            {
                return this.renCtaMoraDiasField;
            }
            set
            {
                this.renCtaMoraDiasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RenCtaMoraDiasAcu
        {
            get
            {
                return this.renCtaMoraDiasAcuField;
            }
            set
            {
                this.renCtaMoraDiasAcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PreRCtaLiqCod
        {
            get
            {
                return this.preRCtaLiqCodField;
            }
            set
            {
                this.preRCtaLiqCodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PreCtaECod
        {
            get
            {
                return this.preCtaECodField;
            }
            set
            {
                this.preCtaECodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double RenSalCap
        {
            get
            {
                return this.renSalCapField;
            }
            set
            {
                this.renSalCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public double RenSalInt
        {
            get
            {
                return this.renSalIntField;
            }
            set
            {
                this.renSalIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public double RenSalIntIVA
        {
            get
            {
                return this.renSalIntIVAField;
            }
            set
            {
                this.renSalIntIVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public double RenSalGas
        {
            get
            {
                return this.renSalGasField;
            }
            set
            {
                this.renSalGasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public double RenSalGasIVA
        {
            get
            {
                return this.renSalGasIVAField;
            }
            set
            {
                this.renSalGasIVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public double RenSalSeg
        {
            get
            {
                return this.renSalSegField;
            }
            set
            {
                this.renSalSegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public double RenPagosCta
        {
            get
            {
                return this.renPagosCtaField;
            }
            set
            {
                this.renPagosCtaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public double RenPagosPunt
        {
            get
            {
                return this.renPagosPuntField;
            }
            set
            {
                this.renPagosPuntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public double RenPagosTot
        {
            get
            {
                return this.renPagosTotField;
            }
            set
            {
                this.renPagosTotField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PPreConsuCli_V2_WS.Execute", WrapperNamespace="GX", IsWrapped=true)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="GX", Order=0)]
        public string Cuit;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(string Cuit)
        {
            this.Cuit = Cuit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PPreConsuCli_V2_WS.ExecuteResponse", WrapperNamespace="GX", IsWrapped=true)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="GX", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WSPreCons", IsNullable=false)]
        public WsAMMA.WSPreConsultaWSPreCons[] Wspreconsulta;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(WsAMMA.WSPreConsultaWSPreCons[] Wspreconsulta)
        {
            this.Wspreconsulta = Wspreconsulta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PPreConsuCli_V2_WSSoapPortChannel : WsAMMA.PPreConsuCli_V2_WSSoapPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PPreConsuCli_V2_WSSoapPortClient : System.ServiceModel.ClientBase<WsAMMA.PPreConsuCli_V2_WSSoapPort>, WsAMMA.PPreConsuCli_V2_WSSoapPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PPreConsuCli_V2_WSSoapPortClient() : 
                base(PPreConsuCli_V2_WSSoapPortClient.GetDefaultBinding(), PPreConsuCli_V2_WSSoapPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PPreConsuCli_V2_WSSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPreConsuCli_V2_WSSoapPortClient(EndpointConfiguration endpointConfiguration) : 
                base(PPreConsuCli_V2_WSSoapPortClient.GetBindingForEndpoint(endpointConfiguration), PPreConsuCli_V2_WSSoapPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPreConsuCli_V2_WSSoapPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PPreConsuCli_V2_WSSoapPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPreConsuCli_V2_WSSoapPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PPreConsuCli_V2_WSSoapPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PPreConsuCli_V2_WSSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsAMMA.ExecuteResponse> WsAMMA.PPreConsuCli_V2_WSSoapPort.ExecuteAsync(WsAMMA.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsAMMA.ExecuteResponse> ExecuteAsync(string Cuit)
        {
            WsAMMA.ExecuteRequest inValue = new WsAMMA.ExecuteRequest();
            inValue.Cuit = Cuit;
            return ((WsAMMA.PPreConsuCli_V2_WSSoapPort)(this)).ExecuteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PPreConsuCli_V2_WSSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PPreConsuCli_V2_WSSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://pesosmar.ddns.net/ppreconsucli_v2_ws.aspx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PPreConsuCli_V2_WSSoapPortClient.GetBindingForEndpoint(EndpointConfiguration.PPreConsuCli_V2_WSSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PPreConsuCli_V2_WSSoapPortClient.GetEndpointAddress(EndpointConfiguration.PPreConsuCli_V2_WSSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PPreConsuCli_V2_WSSoapPort,
        }
    }
}
