// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(SmartClickContext))]
    [Migration("20210809011542_mig8")]
    partial class mig8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Commons.Identity.CommonsFunction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("DeletedById");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("Description");

                    b.Property<bool>("Display");

                    b.Property<string>("LastEditById");

                    b.Property<DateTime>("LastEditTime");

                    b.Property<string>("Name");

                    b.Property<string>("RoutesJson");

                    b.Property<bool>("Show");

                    b.HasKey("Id");

                    b.ToTable("AspNetFunctions");
                });

            modelBuilder.Entity("Commons.Identity.CommonsRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<bool>("Enabled");

                    b.Property<DateTime?>("Expiration");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<bool>("Show");

                    b.Property<string>("ShowName");

                    b.Property<string>("WorkSpaceId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Commons.Identity.CommonsRoleFunction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("FunctionId");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleFunctions");
                });

            modelBuilder.Entity("DAL.Models.Accesos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Coordenadas");

                    b.Property<decimal>("Deuda");

                    b.Property<int?>("EstadoDeudaId");

                    b.Property<DateTime>("FechaHora");

                    b.Property<string>("Observaciones");

                    b.Property<int?>("PuestoId");

                    b.Property<bool>("SinCuentaCorriente");

                    b.Property<int?>("TipoAccesoId");

                    b.Property<string>("Turnos");

                    b.Property<int?>("UATPuestoId");

                    b.Property<bool>("ValidadoPorGPS");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoDeudaId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("TipoAccesoId");

                    b.HasIndex("UATPuestoId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("DAL.Models.Campanas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadPersonas");

                    b.Property<int>("CantidadProvincias");

                    b.Property<int>("CantidadUnidades");

                    b.Property<int?>("EmpresaId");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<decimal>("MaximoDisponible");

                    b.Property<decimal>("MinimoDisponible");

                    b.Property<string>("Observaciones");

                    b.Property<int>("ProvinciaId");

                    b.Property<string>("TextoMail");

                    b.Property<int>("UnidadId");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Campanas");
                });

            modelBuilder.Entity("DAL.Models.CampanasRenglones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int?>("CabeceraId");

                    b.Property<string>("Celular");

                    b.Property<long>("DNI");

                    b.Property<decimal>("Disponible");

                    b.Property<decimal>("ImporteMaximo");

                    b.Property<string>("Nombres");

                    b.Property<string>("Provincia");

                    b.Property<int>("ProvinciaId");

                    b.Property<string>("TipoPersona");

                    b.Property<string>("Unidad");

                    b.Property<int>("UnidadId");

                    b.Property<string>("eMail");

                    b.HasKey("Id");

                    b.HasIndex("CabeceraId");

                    b.ToTable("CampanasRenglones");
                });

            modelBuilder.Entity("DAL.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CBU");

                    b.Property<string>("CategoriaLaboral");

                    b.Property<string>("Celular");

                    b.Property<bool>("ClienteValidado");

                    b.Property<int?>("CodeudorId");

                    b.Property<string>("DestinoLaboral");

                    b.Property<string>("Domicilio");

                    b.Property<int?>("EmpresaId");

                    b.Property<bool>("EsMilitar");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<DateTime>("FechaIngresoLaboral");

                    b.Property<string>("NroDocReferido");

                    b.Property<int>("NumeroAsociado");

                    b.Property<string>("NumeroCliente");

                    b.Property<string>("NumeroLegajoLaboral");

                    b.Property<int?>("PersonaId");

                    b.Property<bool>("PersonaPoliticamenteExpuesta");

                    b.Property<string>("RazonSocial");

                    b.Property<bool>("RecibirPublicidad");

                    b.Property<string>("Telefono");

                    b.Property<int?>("TipoClienteId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("CodeudorId")
                        .IsUnique()
                        .HasFilter("[CodeudorId] IS NOT NULL");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DAL.Models.ClientesServicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ServicioId");

                    b.Property<int?>("TipoClienteId");

                    b.Property<int>("TopeMensual");

                    b.Property<int>("TopeSemanal");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("ClientesServicios");
                });

            modelBuilder.Entity("DAL.Models.Colores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("DAL.Models.Conceptos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<int>("Signo");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("DAL.Models.Core.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("DAL.Models.Core.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasCVU");

                    b.Property<string>("CVU");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("QRCobro");

                    b.Property<decimal>("Saldo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("DAL.Models.Core.ContactosBilletera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<int?>("BilleteraId");

                    b.Property<int?>("ClienteContactoId");

                    b.Property<string>("Detalle");

                    b.Property<DateTime>("FechaCreacion");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("ClienteContactoId");

                    b.ToTable("ContactosBilletera");
                });

            modelBuilder.Entity("DAL.Models.Core.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias");

                    b.Property<int?>("BancoId");

                    b.Property<int?>("BilleteraId");

                    b.Property<string>("CBU");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Numero");

                    b.Property<bool>("Terceros");

                    b.Property<string>("Titular");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("BilleteraId");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("DAL.Models.Core.InstitucionFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("InstitucionesFinancieras");
                });

            modelBuilder.Entity("DAL.Models.Core.MovimientoBilletera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BilleteraId");

                    b.Property<string>("CBU");

                    b.Property<int?>("CuentaBancariaId");

                    b.Property<DateTime>("Fecha");

                    b.Property<decimal>("Monto");

                    b.Property<int?>("OrigenAsociadoId");

                    b.Property<string>("QR");

                    b.Property<int?>("TarjetaId");

                    b.Property<int?>("TipoMovimientoId");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("OrigenAsociadoId");

                    b.HasIndex("TarjetaId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("MovimientosBilletera");
                });

            modelBuilder.Entity("DAL.Models.Core.OrigenMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("IdAsociado");

                    b.Property<int>("TipoOrigen");

                    b.HasKey("Id");

                    b.ToTable("OrigenMovimiento");
                });

            modelBuilder.Entity("DAL.Models.Core.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("DescripcionAmpliada");

                    b.Property<byte[]>("Foto");

                    b.Property<decimal>("Precio");

                    b.Property<int?>("ProveedorId");

                    b.Property<int?>("RubroId");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DAL.Models.Core.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<long>("CUIT");

                    b.Property<string>("Domicilio");

                    b.Property<int?>("EmpresaId");

                    b.Property<string>("Nombre");

                    b.Property<string>("RazonSocial");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("DAL.Models.Core.ProveedorRubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProveedorId");

                    b.Property<int?>("RubroId");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RubroId");

                    b.ToTable("ProveedorRubros");
                });

            modelBuilder.Entity("DAL.Models.Core.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("DAL.Models.Core.ServicioBilletera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BilleteraId");

                    b.Property<string>("CodigoServicioFactura");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("ServiciosBilletera");
                });

            modelBuilder.Entity("DAL.Models.Core.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BancoId");

                    b.Property<int?>("BilleteraId");

                    b.Property<int?>("InstitucionFinancieraId");

                    b.Property<string>("Numero");

                    b.Property<string>("Titular");

                    b.Property<string>("Vencimiento");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("InstitucionFinancieraId");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("DAL.Models.Core.TipoMovimientoBilletera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Credito");

                    b.Property<bool>("Debito");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimientoBilletera");
                });

            modelBuilder.Entity("DAL.Models.CuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<int?>("ConceptoId");

                    b.Property<DateTime>("Fecha");

                    b.Property<decimal>("Importe");

                    b.Property<string>("Observaciones");

                    b.Property<decimal>("Saldo");

                    b.Property<DateTime?>("Vencimiento");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConceptoId");

                    b.ToTable("CuentaCorriente");
                });

            modelBuilder.Entity("DAL.Models.CuentasCorrientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<decimal>("Credito");

                    b.Property<decimal>("Debito");

                    b.Property<DateTime?>("Fecha");

                    b.Property<int?>("PrestamoId");

                    b.Property<decimal>("Saldo");

                    b.Property<int?>("TipoMovimientoId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("CuentasCorrientes");
                });

            modelBuilder.Entity("DAL.Models.DatosEstructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CBU");

                    b.Property<string>("CUIT");

                    b.Property<string>("Calle");

                    b.Property<string>("CodigoPostal");

                    b.Property<string>("Convenio");

                    b.Property<string>("CredencialReportes");

                    b.Property<string>("Entidad");

                    b.Property<string>("FAX");

                    b.Property<string>("Localidad");

                    b.Property<string>("NombreDependencia");

                    b.Property<string>("NombreOrganismo");

                    b.Property<string>("Numero");

                    b.Property<string>("Provincia");

                    b.Property<string>("Sigla");

                    b.Property<string>("Sucursal");

                    b.Property<string>("Telefono");

                    b.Property<string>("URLReportes");

                    b.Property<string>("UsuarioReportes");

                    b.HasKey("Id");

                    b.ToTable("DatosEstructura");
                });

            modelBuilder.Entity("DAL.Models.DestinosFondos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("DestinoFondos");
                });

            modelBuilder.Entity("DAL.Models.DestinosFondosRubros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DestinosFondosId");

                    b.Property<int?>("RubroId");

                    b.HasKey("Id");

                    b.HasIndex("DestinosFondosId");

                    b.HasIndex("RubroId");

                    b.ToTable("DestinoFondosRubros");
                });

            modelBuilder.Entity("DAL.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<long>("CUIT");

                    b.Property<string>("ColorBotones");

                    b.Property<string>("ColorCarnet");

                    b.Property<string>("ColorFondo");

                    b.Property<string>("ColorFontCarnet");

                    b.Property<string>("ColorLogin");

                    b.Property<string>("Domicilio");

                    b.Property<int>("EntidadIdCGE");

                    b.Property<string>("Facebook");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<byte[]>("FondoMobile");

                    b.Property<byte[]>("GIFLogoMutual");

                    b.Property<int?>("GrupoId");

                    b.Property<byte[]>("ImagenLogin");

                    b.Property<string>("Instagram");

                    b.Property<byte[]>("LogoMutual");

                    b.Property<string>("Mail");

                    b.Property<string>("PasswordCGE");

                    b.Property<string>("RazonSocial");

                    b.Property<string>("Telefono");

                    b.Property<string>("TokenCGE");

                    b.Property<string>("Twitter");

                    b.Property<string>("WhatsApp");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("DAL.Models.EstadosCiviles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("DAL.Models.EstadosDeudas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("EstadosDeudas");
                });

            modelBuilder.Entity("DAL.Models.EstadosPrestamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AnulablePersona");

                    b.Property<string>("Color");

                    b.Property<bool>("ConfirmablePersona");

                    b.Property<int>("EstadoCGEId");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Transferido");

                    b.HasKey("Id");

                    b.ToTable("EstadosPrestamos");
                });

            modelBuilder.Entity("DAL.Models.FormasPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("DAL.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("DAL.Models.Grupos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("DAL.Models.Horarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<int>("DiaSemana");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<string>("Nombre");

                    b.Property<int>("Orden");

                    b.Property<int?>("ServicioId");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("DAL.Models.Invitaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<DateTime?>("Baja");

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime?>("Completado");

                    b.Property<DateTime>("Desde");

                    b.Property<int>("Estado");

                    b.Property<byte[]>("Foto");

                    b.Property<string>("Hash");

                    b.Property<DateTime>("Hasta");

                    b.Property<string>("Link");

                    b.Property<string>("Nombres");

                    b.Property<long>("NumeroDocumento");

                    b.Property<string>("Observaciones");

                    b.Property<string>("Patente");

                    b.Property<string>("QR");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("DAL.Models.LineasPrestamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadCuotasMaxima");

                    b.Property<int>("CantidadCuotasMinima");

                    b.Property<decimal>("CapitalMaximo");

                    b.Property<decimal>("CapitalMinimo");

                    b.Property<decimal>("CuotaMaxima");

                    b.Property<decimal>("CuotaMinima");

                    b.Property<int?>("MonedaId");

                    b.Property<string>("Nombre");

                    b.Property<int?>("SistemaFinanciacionId");

                    b.Property<int>("TipoDescuentoCGEId");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("SistemaFinanciacionId");

                    b.ToTable("LineasPrestamos");
                });

            modelBuilder.Entity("DAL.Models.LineasPrestamosPlanes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CFT");

                    b.Property<int>("CantidadCuotas");

                    b.Property<int?>("LineaId");

                    b.Property<decimal>("MargenDisponible");

                    b.Property<decimal>("MontoCuota");

                    b.Property<decimal>("MontoPrestado");

                    b.HasKey("Id");

                    b.HasIndex("LineaId");

                    b.ToTable("LineasPrestamosPlanes");
                });

            modelBuilder.Entity("DAL.Models.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("IdDepartamento");

                    b.Property<int>("IdProvincia");

                    b.Property<string>("Latitud");

                    b.Property<string>("Longitud");

                    b.Property<string>("ProvinciaNombre");

                    b.HasKey("Id");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("DAL.Models.MatrizConsecuencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("MatrizConsecuencias");
                });

            modelBuilder.Entity("DAL.Models.MatrizProbabilidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("MatrizProbabilidades");
                });

            modelBuilder.Entity("DAL.Models.MatrizRiesgoCabecera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<bool>("CuentaCorrienteDolares");

                    b.Property<bool>("CuentaCorrientePesos");

                    b.Property<bool>("DeclaraBienesInmuebles");

                    b.Property<bool>("DeclaraBienesMueblesRegistrables");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("FrecuenciaAnualCreditos");

                    b.Property<bool>("OtrasInversiones");

                    b.Property<int?>("PrestamoId");

                    b.Property<bool>("ResidenteZonaLimistrofe");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("MatrizRiesgoCabeceras");
                });

            modelBuilder.Entity("DAL.Models.MatrizRiesgoRenglones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CabeceraId");

                    b.Property<int?>("ConsecuenciaId");

                    b.Property<int?>("ProbabilidadId");

                    b.HasKey("Id");

                    b.HasIndex("CabeceraId");

                    b.HasIndex("ConsecuenciaId");

                    b.HasIndex("ProbabilidadId");

                    b.ToTable("MatrizRiesgoRenglones");
                });

            modelBuilder.Entity("DAL.Models.MockServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoBarras");

                    b.Property<string>("CodigoServicioFactura");

                    b.Property<decimal>("Monto");

                    b.Property<string>("NombreServicio");

                    b.HasKey("Id");

                    b.ToTable("MockServicios");
                });

            modelBuilder.Entity("DAL.Models.Monedas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("DAL.Models.NotificacionesPersonas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("FechaHora");

                    b.Property<string>("Titulo");

                    b.Property<DateTime?>("TomaConocimiento");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("NotificacionesPersonas");
                });

            modelBuilder.Entity("DAL.Models.Novedades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ColorId");

                    b.Property<int?>("EmpresaId");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Foto");

                    b.Property<bool>("Publica");

                    b.Property<string>("Texto");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("DAL.Models.Organismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<string>("Descripcion");

                    b.Property<int>("Orden");

                    b.HasKey("Id");

                    b.ToTable("Organismos");
                });

            modelBuilder.Entity("DAL.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("DAL.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<int>("CantidadHijos");

                    b.Property<string>("Cuil");

                    b.Property<int?>("EstadoCivilId");

                    b.Property<DateTime>("FechaActualizacion");

                    b.Property<DateTime?>("FechaNacimiento");

                    b.Property<byte[]>("Foto");

                    b.Property<int?>("GeneroId");

                    b.Property<string>("Nombres")
                        .IsRequired();

                    b.Property<string>("NroDocumento");

                    b.Property<int?>("PaisId");

                    b.Property<int?>("TipoDocumentoId");

                    b.Property<int?>("TipoPersonaId");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PaisId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoPersonaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("DAL.Models.Prestamos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AprobadoPorId");

                    b.Property<string>("CBU");

                    b.Property<decimal>("CFT");

                    b.Property<int>("CantidadCuotas");

                    b.Property<decimal>("Capital");

                    b.Property<string>("CapitalEnLetras");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("CuotasEnLetras");

                    b.Property<int>("CuotasRestantes");

                    b.Property<int?>("DestinoFondosId");

                    b.Property<string>("Domicilio");

                    b.Property<int?>("EstadoActualId");

                    b.Property<DateTime?>("FechaAnulacion");

                    b.Property<DateTime?>("FechaAprobacion");

                    b.Property<DateTime?>("FechaLiquidacion");

                    b.Property<DateTime?>("FechaPago");

                    b.Property<DateTime?>("FechaPrimerVencimiento");

                    b.Property<DateTime?>("FechaSolicitado");

                    b.Property<byte[]>("FirmaOlografica");

                    b.Property<byte[]>("FirmaOlograficaConfirmacion");

                    b.Property<int?>("FormaPagoId");

                    b.Property<byte[]>("FotoDNIAnverso");

                    b.Property<byte[]>("FotoDNIReverso");

                    b.Property<byte[]>("FotoSosteniendoDNI");

                    b.Property<string>("IngresadoPorId");

                    b.Property<byte[]>("LegajoElectronico");

                    b.Property<int?>("LineaId");

                    b.Property<string>("LiquidadoPorId");

                    b.Property<decimal>("MontoCuota");

                    b.Property<string>("MontoCuotaEnLetras");

                    b.Property<string>("Observaciones");

                    b.Property<string>("ObservacionesAnulacion");

                    b.Property<string>("OficialCuentaId");

                    b.Property<int>("PrestamoCGEId");

                    b.Property<int>("PrestamoNumero");

                    b.Property<decimal>("Saldo");

                    b.Property<int?>("VendedorId");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinoFondosId");

                    b.HasIndex("EstadoActualId");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("IngresadoPorId");

                    b.HasIndex("LineaId");

                    b.HasIndex("LiquidadoPorId");

                    b.HasIndex("OficialCuentaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("DAL.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("DescripcionCompleta");

                    b.Property<string>("Latitud");

                    b.Property<string>("Longitud");

                    b.HasKey("Id");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("DAL.Models.Puestos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coordenadas");

                    b.Property<int?>("EmpresaId");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<string>("Nombre");

                    b.Property<int?>("TipoId");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("DAL.Models.PuestosCodigos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashQR");

                    b.Property<byte[]>("Imagen");

                    b.Property<int?>("PuestoId");

                    b.Property<DateTime>("ValidoDesde");

                    b.Property<DateTime>("ValidoHasta");

                    b.HasKey("Id");

                    b.HasIndex("PuestoId");

                    b.ToTable("PuestosCodigos");
                });

            modelBuilder.Entity("DAL.Models.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteAnulaId");

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime?>("FechaAnulada");

                    b.Property<int?>("HorarioId");

                    b.Property<string>("Observaciones");

                    b.HasKey("Id");

                    b.HasIndex("ClienteAnulaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HorarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("DAL.Models.Servicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<int>("Cupo");

                    b.Property<int>("DiasProgramacion");

                    b.Property<int?>("EmpresaId");

                    b.Property<DateTime?>("FechaBaja");

                    b.Property<DateTime?>("FechaUnica");

                    b.Property<byte[]>("Icono");

                    b.Property<string>("Nombre");

                    b.Property<string>("Observaciones");

                    b.Property<int?>("TipoId");

                    b.Property<int>("TopeAnualFinde");

                    b.Property<int>("TopeAnualSemana");

                    b.Property<int>("TopeMensualFinde");

                    b.Property<int>("TopeMensualSemana");

                    b.Property<int>("TopePendienteFinde");

                    b.Property<int>("TopePendienteGlobal");

                    b.Property<int>("TopePendienteSemana");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("DAL.Models.SistemasFinanciacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("SistemasFinanciacion");
                });

            modelBuilder.Entity("DAL.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("DAL.Models.TipoPuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoPuesto");
                });

            modelBuilder.Entity("DAL.Models.TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoServicio");
                });

            modelBuilder.Entity("DAL.Models.TiposAccesos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TiposAccesos");
                });

            modelBuilder.Entity("DAL.Models.TiposClientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadActividadesSemanales");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TiposClientes");
                });

            modelBuilder.Entity("DAL.Models.TiposMovimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Credito");

                    b.Property<bool>("Debito");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TiposMovimientos");
                });

            modelBuilder.Entity("DAL.Models.TiposPersonas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LimiteCuotas");

                    b.Property<int?>("OrganismoId");

                    b.Property<decimal>("TopePrestamo");

                    b.Property<string>("nombre");

                    b.HasKey("Id");

                    b.HasIndex("OrganismoId");

                    b.ToTable("TiposPersonas");
                });

            modelBuilder.Entity("DAL.Models.UAT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("FechaHora");

                    b.Property<int?>("PersonaId");

                    b.Property<string>("Token");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UAT");
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DeviceId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Mail");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("Password");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<int?>("ProveedorId");

                    b.Property<bool>("RecordarPassword");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Token");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int?>("VendedoresId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("VendedoresId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DAL.Models.Vendedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Domicilio");

                    b.Property<string>("Mail");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Commons.Identity.CommonsRoleFunction", b =>
                {
                    b.HasOne("Commons.Identity.CommonsFunction", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("Commons.Identity.CommonsRole", "Role")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("DAL.Models.Accesos", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.EstadosDeudas", "EstadoDeuda")
                        .WithMany()
                        .HasForeignKey("EstadoDeudaId");

                    b.HasOne("DAL.Models.Puestos", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("DAL.Models.TiposAccesos", "TipoAcceso")
                        .WithMany()
                        .HasForeignKey("TipoAccesoId");

                    b.HasOne("DAL.Models.UAT", "UATPuesto")
                        .WithMany()
                        .HasForeignKey("UATPuestoId");
                });

            modelBuilder.Entity("DAL.Models.Campanas", b =>
                {
                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("DAL.Models.CampanasRenglones", b =>
                {
                    b.HasOne("DAL.Models.Campanas", "Cabecera")
                        .WithMany()
                        .HasForeignKey("CabeceraId");
                });

            modelBuilder.Entity("DAL.Models.Clientes", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Codeudor")
                        .WithOne("DependeDe")
                        .HasForeignKey("DAL.Models.Clientes", "CodeudorId");

                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("DAL.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("DAL.Models.TiposClientes", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.HasOne("DAL.Models.Usuario", "Usuario")
                        .WithOne("Clientes")
                        .HasForeignKey("DAL.Models.Clientes", "UsuarioId");
                });

            modelBuilder.Entity("DAL.Models.ClientesServicios", b =>
                {
                    b.HasOne("DAL.Models.Servicios", "Servicio")
                        .WithMany("TiposSocios")
                        .HasForeignKey("ServicioId");

                    b.HasOne("DAL.Models.TiposClientes", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");
                });

            modelBuilder.Entity("DAL.Models.Core.Billetera", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("DAL.Models.Core.ContactosBilletera", b =>
                {
                    b.HasOne("DAL.Models.Core.Billetera")
                        .WithMany("Contactos")
                        .HasForeignKey("BilleteraId");

                    b.HasOne("DAL.Models.Clientes", "ClienteContacto")
                        .WithMany()
                        .HasForeignKey("ClienteContactoId");
                });

            modelBuilder.Entity("DAL.Models.Core.CuentaBancaria", b =>
                {
                    b.HasOne("DAL.Models.Core.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId");

                    b.HasOne("DAL.Models.Core.Billetera")
                        .WithMany("Cuentas")
                        .HasForeignKey("BilleteraId");
                });

            modelBuilder.Entity("DAL.Models.Core.MovimientoBilletera", b =>
                {
                    b.HasOne("DAL.Models.Core.Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId");

                    b.HasOne("DAL.Models.Core.CuentaBancaria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaBancariaId");

                    b.HasOne("DAL.Models.Core.OrigenMovimiento", "OrigenAsociado")
                        .WithMany()
                        .HasForeignKey("OrigenAsociadoId");

                    b.HasOne("DAL.Models.Core.Tarjeta")
                        .WithMany("Movimientos")
                        .HasForeignKey("TarjetaId");

                    b.HasOne("DAL.Models.Core.TipoMovimientoBilletera", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId");
                });

            modelBuilder.Entity("DAL.Models.Core.Producto", b =>
                {
                    b.HasOne("DAL.Models.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.HasOne("DAL.Models.Core.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId");
                });

            modelBuilder.Entity("DAL.Models.Core.Proveedor", b =>
                {
                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("DAL.Models.Core.ProveedorRubro", b =>
                {
                    b.HasOne("DAL.Models.Core.Proveedor", "Proveedor")
                        .WithMany("Rubros")
                        .HasForeignKey("ProveedorId");

                    b.HasOne("DAL.Models.Core.Rubro", "Rubro")
                        .WithMany("Proveedores")
                        .HasForeignKey("RubroId");
                });

            modelBuilder.Entity("DAL.Models.Core.ServicioBilletera", b =>
                {
                    b.HasOne("DAL.Models.Core.Billetera")
                        .WithMany("Servicios")
                        .HasForeignKey("BilleteraId");
                });

            modelBuilder.Entity("DAL.Models.Core.Tarjeta", b =>
                {
                    b.HasOne("DAL.Models.Core.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId");

                    b.HasOne("DAL.Models.Core.Billetera")
                        .WithMany("Tarjetas")
                        .HasForeignKey("BilleteraId");

                    b.HasOne("DAL.Models.Core.InstitucionFinanciera", "InstitucionFinanciera")
                        .WithMany()
                        .HasForeignKey("InstitucionFinancieraId");
                });

            modelBuilder.Entity("DAL.Models.CuentaCorriente", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.Conceptos", "Concepto")
                        .WithMany()
                        .HasForeignKey("ConceptoId");
                });

            modelBuilder.Entity("DAL.Models.CuentasCorrientes", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.Prestamos", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("DAL.Models.TiposMovimientos", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId");
                });

            modelBuilder.Entity("DAL.Models.DestinosFondosRubros", b =>
                {
                    b.HasOne("DAL.Models.DestinosFondos", "DestinosFondos")
                        .WithMany("DestinosFondosRubros")
                        .HasForeignKey("DestinosFondosId");

                    b.HasOne("DAL.Models.Core.Rubro", "Rubro")
                        .WithMany()
                        .HasForeignKey("RubroId");
                });

            modelBuilder.Entity("DAL.Models.Empresas", b =>
                {
                    b.HasOne("DAL.Models.Grupos", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId");
                });

            modelBuilder.Entity("DAL.Models.Horarios", b =>
                {
                    b.HasOne("DAL.Models.Servicios", "Servicio")
                        .WithMany("Horario")
                        .HasForeignKey("ServicioId");
                });

            modelBuilder.Entity("DAL.Models.Invitaciones", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("DAL.Models.LineasPrestamos", b =>
                {
                    b.HasOne("DAL.Models.Monedas", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId");

                    b.HasOne("DAL.Models.SistemasFinanciacion", "SistemaFinanciacion")
                        .WithMany()
                        .HasForeignKey("SistemaFinanciacionId");
                });

            modelBuilder.Entity("DAL.Models.LineasPrestamosPlanes", b =>
                {
                    b.HasOne("DAL.Models.LineasPrestamos", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId");
                });

            modelBuilder.Entity("DAL.Models.MatrizRiesgoCabecera", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.Prestamos", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");
                });

            modelBuilder.Entity("DAL.Models.MatrizRiesgoRenglones", b =>
                {
                    b.HasOne("DAL.Models.MatrizRiesgoCabecera", "Cabecera")
                        .WithMany()
                        .HasForeignKey("CabeceraId");

                    b.HasOne("DAL.Models.MatrizConsecuencias", "Consecuencia")
                        .WithMany()
                        .HasForeignKey("ConsecuenciaId");

                    b.HasOne("DAL.Models.MatrizProbabilidades", "Probabilidad")
                        .WithMany()
                        .HasForeignKey("ProbabilidadId");
                });

            modelBuilder.Entity("DAL.Models.NotificacionesPersonas", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("DAL.Models.Novedades", b =>
                {
                    b.HasOne("DAL.Models.Colores", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("DAL.Models.Persona", b =>
                {
                    b.HasOne("DAL.Models.EstadosCiviles", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId");

                    b.HasOne("DAL.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId");

                    b.HasOne("DAL.Models.Paises", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.HasOne("DAL.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId");

                    b.HasOne("DAL.Models.TiposPersonas", "TipoPersona")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId");
                });

            modelBuilder.Entity("DAL.Models.Prestamos", b =>
                {
                    b.HasOne("DAL.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId");

                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.DestinosFondos", "DestinoFondos")
                        .WithMany()
                        .HasForeignKey("DestinoFondosId");

                    b.HasOne("DAL.Models.EstadosPrestamos", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoActualId");

                    b.HasOne("DAL.Models.FormasPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId");

                    b.HasOne("DAL.Models.Usuario", "IngresadoPor")
                        .WithMany()
                        .HasForeignKey("IngresadoPorId");

                    b.HasOne("DAL.Models.LineasPrestamos", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId");

                    b.HasOne("DAL.Models.Usuario", "LiquidadoPor")
                        .WithMany()
                        .HasForeignKey("LiquidadoPorId");

                    b.HasOne("DAL.Models.Usuario", "OficialCuenta")
                        .WithMany()
                        .HasForeignKey("OficialCuentaId");

                    b.HasOne("DAL.Models.Vendedores", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("DAL.Models.Puestos", b =>
                {
                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("DAL.Models.TipoPuesto", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("DAL.Models.PuestosCodigos", b =>
                {
                    b.HasOne("DAL.Models.Puestos", "Puesto")
                        .WithMany("PuestoCodigos")
                        .HasForeignKey("PuestoId");
                });

            modelBuilder.Entity("DAL.Models.Reservas", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "ClienteAnula")
                        .WithMany()
                        .HasForeignKey("ClienteAnulaId");

                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.Horarios", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId");
                });

            modelBuilder.Entity("DAL.Models.Servicios", b =>
                {
                    b.HasOne("DAL.Models.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("DAL.Models.TipoServicio", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("DAL.Models.TiposPersonas", b =>
                {
                    b.HasOne("DAL.Models.Organismo", "Organismo")
                        .WithMany()
                        .HasForeignKey("OrganismoId");
                });

            modelBuilder.Entity("DAL.Models.UAT", b =>
                {
                    b.HasOne("DAL.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("DAL.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("DAL.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("DAL.Models.Usuario", b =>
                {
                    b.HasOne("DAL.Models.Core.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.HasOne("DAL.Models.Vendedores", "Vendedores")
                        .WithMany()
                        .HasForeignKey("VendedoresId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Commons.Identity.CommonsRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Commons.Identity.CommonsRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
