using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Text;

namespace DAL.DTOs.Plenario
{

    public class TokenValoresPosibles
    {
        public string Token { get; set; }
        public bool boolGenerarCredito { get; set; }
        public bool boolOtorgarCredito { get; set; }
        public bool boolGenerarOrdendePago { get; set; }
        public bool boolLiquidarOrdenPago { get; set; }
        public int Id_Banco { get; set; }
        public bool IsWorkFlow { get; set; }
        public bool updateWithModel { get; set; }
    }

    public class PrestamosSolicitud
    {
        public int Id { get; set; }
        public int Id_Actividad { get; set; }
        public int id_Actividad_Lab { get; set; }
        public int Id_CentroDeCosto { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Cobranza { get; set; }
        public int Id_Comercializador { get; set; }
        public int Id_Entidad { get; set; }
        public int Id_Especie { get; set; }
        public int Id_Estado { get; set; }
        public int? Id_Flujos_Estados { get; set; }
        public int Id_Estado_Rechazo { get; set; }
        public int Id_GPais { get; set; }
        public int Id_GProvincia { get; set; }
        public int Id_GProvincia_Lab { get; set; }
        public int Id_Linea { get; set; }
        public int Id_Linea_Bullet { get; set; }
        public int Id_Linea_Liquidacion { get; set; }
        public int Id_LineaCosto { get; set; }
        public int Id_Marca { get; set; }
        public string Id_Marca_FechaAdd { get; set; }
        public int? Id_MedioDePagoOtorgamiento { get; set; }
        public int? Id_MediosdeCobro { get; set; }
        public int id_NroDoc_Version { get; set; }
        public int Id_OrigenFondos { get; set; }
        public int Id_Otorgamiento { get; set; }
        public int Id_Pais { get; set; }
        public int Id_Poliza { get; set; }
        public int Id_Prestador { get; set; }
        public int id_Prestamos_Fines { get; set; }
        public int Id_Provincia { get; set; }
        public int Id_Provincia_Lab { get; set; }
        public int Id_R1Provincia { get; set; }
        public int Id_R2Provincia { get; set; }
        public int Id_ReciboHaberes { get; set; }
        public int Id_Seguro { get; set; }
        public int Id_Sucursal { get; set; }
        public string Id_Terceros { get; set; }
        public int Id_Tipo_Calculo { get; set; }
        public int Id_Tipo_Credito { get; set; }
        public int Id_TipoIva { get; set; }
        public int Id_TipoIva_Garante { get; set; }
        public int Id_TipoPersona { get; set; }
        public int AccionesIntegradas { get; set; }
        public string Alias { get; set; }
        public decimal Alquila_CuantoPaga { get; set; }
        public decimal Anticipo { get; set; }
        public string AntiguedadDomicilio { get; set; }
        public decimal AntiguedadLaboral { get; set; }
        public string Apellido { get; set; }
        public string CApellido { get; set; }
        public decimal CapitalCooperativo { get; set; }
        public decimal CasaPropia_CuantoPaga { get; set; }
        public string CDocumento { get; set; }
        public string CFechaNacimiento { get; set; }
        public decimal CFT { get; set; }
        public string ClienteInstFinanc { get; set; }
        public string CNombre { get; set; }
        public int? CobroPorResumen { get; set; }
        [Display(Name = "Código postal", Prompt = "Ingresar")]
        public string CodigoPostal { get; set; }
        public string CodigoPostal_Lab { get; set; }
        public int CodigoPostalNroHipotecario { get; set; }
        public string CodigoReferencia { get; set; }
        public string CSexo { get; set; }
        public string CTelefono { get; set; }
        public string CTelefonoCel { get; set; }
        public string CTelefonoLab { get; set; }
        public string CTelefonoPart { get; set; }
        public string CtrlDigital { get; set; }
        public string CtrlManual { get; set; }
        public string Cuit { get; set; }
        public string CuitLaboral { get; set; }
        public decimal Cupo { get; set; }
        public string Datos_Contacto { get; set; }
        public string Detalle_Autorizado { get; set; }
        public string Detalle_Cancelacion { get; set; }
        public string Domicilio { get; set; }
        public string Domicilio_Barrio { get; set; }
        public string Domicilio_Dpto { get; set; }
        public string Domicilio_Entre_Calle_1 { get; set; }
        public string Domicilio_Entre_Calle_2 { get; set; }
        public string Domicilio_Lab { get; set; }
        public string Domicilio_Nro { get; set; }
        public string Domicilio_Piso { get; set; }
        public string DomicilioPostal { get; set; }
        public string Empresa { get; set; }
        public string EstadoCivil { get; set; }
        public string Fecha_1Vto { get; set; }
        public string Fecha_Autorizado { get; set; }
        public string Fecha_CtrlDigital { get; set; }
        public string Fecha_Ctrlmanual { get; set; }
        public string FechaIngresoConyuge { get; set; }
        public string FechaInicioLaboral { get; set; }
        public string FechaNacimiento { get; set; }
        public string FechaOperacion { get; set; }
        public decimal GAntLaboral { get; set; }
        public string GApellido { get; set; }
        public decimal Gastos_Cuotas { get; set; }
        public decimal Gastos_Escribania { get; set; }
        public decimal Gastos_MediosDePago { get; set; }
        public decimal Gastos_Otorgamiento { get; set; }
        public decimal Gastos_Otros { get; set; }
        public decimal Gastos_Otros2 { get; set; }
        public decimal Gastos_Otros3 { get; set; }
        public decimal Gastos_Primera_Cuota { get; set; }
        public decimal Gastos_Primera_Cuota_Porc { get; set; }
        public decimal Gastos_Refinanciacion { get; set; }
        public decimal Gastos_Seguro { get; set; }
        public decimal Gastos_Sellado { get; set; }
        public decimal Gastos_Servicio { get; set; }
        public string GCodigoPostal { get; set; }
        public string GCodigoPostal_Lab { get; set; }
        public string GCuit { get; set; }
        public string GCUIT_Lab { get; set; }
        public string GDomicilio { get; set; }
        public string GDomicilio_Lab { get; set; }
        public string GEmpresa { get; set; }
        public string GEstadoCivil { get; set; }
        public string GFechaInicio_Lab { get; set; }
        public string GFechaNacimiento { get; set; }
        public int Gid_Codigo_Descuento { get; set; }
        public int GId_Entidad_CodDesc { get; set; }
        public string GLocalidad { get; set; }
        public string GLocalidad_Lab { get; set; }
        public string GNombre { get; set; }
        public string GNro_Certificado { get; set; }
        public int GNroDoc { get; set; }
        public string GPuesto_Lab { get; set; }
        public string GRelacion { get; set; }
        public string GSexo { get; set; }
        public decimal Gsueldo_Lab { get; set; }
        public string GTelefono { get; set; }
        public string GTelefono_Lab { get; set; }
        public string GTipoDoc { get; set; }
        public int Hijos { get; set; }
        public decimal Importe { get; set; }
        public bool Impreso { get; set; }
        public bool IncluirSueldoConyuge { get; set; }
        public bool InmueblePago { get; set; }
        public string Laboral_Telefono2 { get; set; }
        public string Localidad { get; set; }
        public string Localidad_Lab { get; set; }
        public string Mail { get; set; }
        public string MotivoDeRechazo { get; set; }
        public string Nombre { get; set; }
        public string NombreMadre { get; set; }
        public string NombrePadre { get; set; }
        public string NroBeneficiario { get; set; }
        public string NroCbu { get; set; }
        public int Nrocredito { get; set; }
        public int NroCreditoBullet { get; set; }
        public int NroDoc { get; set; }
        public string NroLegajo { get; set; }
        public string Observaciones { get; set; }
        public string PerfilFinanciero { get; set; }
        public decimal Plazo { get; set; }
        public decimal Porc_Gastos { get; set; }
        public decimal Porc_Iva { get; set; }
        public decimal Porc_Seguro { get; set; }
        public decimal Porc_Sellado { get; set; }
        public decimal Precio_Venta { get; set; }
        public string PrestamoPersonal_Banco1 { get; set; }
        public string PrestamoPersonal_Banco2 { get; set; }
        public string PrestamoPrendario_Banco1 { get; set; }
        public string PrestamoPrendario_Banco2 { get; set; }
        public decimal PTasa_Costo { get; set; }
        public string PuestoOcupa { get; set; }
        public string R1Apellido { get; set; }
        public string R1CodigoPostal { get; set; }
        public string R1Domicilio { get; set; }
        public string R1Localidad { get; set; }
        public string R1mail { get; set; }
        public string R1Nombre { get; set; }
        public string R1Relacion { get; set; }
        public string R1TelefonoCel { get; set; }
        public string R1TelefonoLab { get; set; }
        public string R1TelefonoPart { get; set; }
        public string R2Apellido { get; set; }
        public string R2CodigoPostal { get; set; }
        public string R2Domicilio { get; set; }
        public string R2Localidad { get; set; }
        public string R2mail { get; set; }
        public string R2Nombre { get; set; }
        public string R2Relacion { get; set; }
        public string R2TelefonoCel { get; set; }
        public string R2TelefonoLab { get; set; }
        public string R2TelefonoPart { get; set; }
        public string Rechazo_Observaciones { get; set; }
        public string Referente1FecNac { get; set; }
        public int? Referente1NroDoc { get; set; }
        public string Referente1TipoDoc { get; set; }
        public string Referente2FecNac { get; set; }
        public int? Referente2NroDoc { get; set; }
        public string Referente2TipoDoc { get; set; }
        public string Sexo { get; set; }
        public decimal Sueldo { get; set; }
        public decimal SueldoConyuge { get; set; }
        public string TajetaCredito_Banco1 { get; set; }
        public string TajetaCredito_Banco2 { get; set; }
        public decimal Tasa { get; set; }
        public string Telefono { get; set; }
        public string Telefono_Lab { get; set; }
        public bool Telefono_No_Propio { get; set; }
        public string Telefono_No_Propio_Apellido { get; set; }
        public string Telefono_No_Propio_Direccion { get; set; }
        public string Telefono_No_Propio_Nombre { get; set; }
        public string TelefonoCel { get; set; }
        public decimal TEM { get; set; }
        public string TipoDoc { get; set; }
        public string TipoDocConyuge { get; set; }
        public bool TipoInmueble { get; set; }
        public string TipoRelacionLaboral { get; set; }
        public string TipoRelacionLaboral_Conyuge { get; set; }
        public decimal Valor_Cuota_Costo { get; set; }
        public decimal ValorAccion { get; set; }
        public decimal ValorCuota { get; set; }
        public decimal ValorCuota_Final { get; set; }
        public string VerDocConyuge { get; set; }
        public string User_Autorizado { get; set; }
        public string User_CtrlDigital { get; set; }
        public string User_CtrlManual { get; set; }
        public string UserAdd { get; set; }
        public string UserMod { get; set; }
        public int Id_Usuario_Add { get; set; }
        public int Id_Usuario_Mod { get; set; }
        public string FechaAdd { get; set; }
        public string FechaMod { get; set; }
        public int LibroAsoc_TipoSuscripcion { get; set; }
        public int? Id_Producto { get; set; }
        public bool Gasto_Sellado_IncluyeIVA { get; set; }
        public bool Gasto_Escribania_IncluyeIVA { get; set; }
        public bool Gasto_Otorgamiento_IncluyeIVA { get; set; }
        public string Fecha_Cobro_GastoOtorg { get; set; }
        public int Porce_Capital_Cuota_Impar { get; set; }
        public int Porce_Capital_Cuota_Par { get; set; }
        public string Fecha_LiquidacionGastos { get; set; }
        public string FechaCambioEstado { get; set; }
        public int? Id_Usuario_Asignado { get; set; }
        public string Fecha_Asignado { get; set; }
    }


    public class OperationResult
    {

        public HttpStatusCode statusCode { get; set; }
        public string statusMessage { get; set; }
        internal bool handled { get; set; }
        internal int Codigo { get; set; }
        public PrestamosSolicitud content { get; set; }

    }


}
